services:
  # Frontend development server
  client-dev:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    networks:
      - dev-network

  # Backend development server
  server-dev:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
      - /app/node_modules
      - /app/dist
    environment:
      - NODE_ENV=development
      - CLIENT_URL=http://localhost:3000
      - PORT=8000
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge 