services:
  # Frontend build container
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - client_dist:/app/dist
    networks:
      - app-network

  # Backend API server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    expose:
      - "8000"
    environment:
      - NODE_ENV=production
      - CLIENT_URL=https://localhost
      - PORT=8000
    networks:
      - app-network

  # Nginx reverse proxy and static file server
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - client_dist:/usr/share/nginx/html
    depends_on:
      - client
      - server
    networks:
      - app-network

volumes:
  client_dist:

networks:
  app-network:
    driver: bridge 